[env:esp32-c6-devkitc-1]
platform = https://github.com/pioarduino/platform-espressif32.git
board = esp32-c6-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600

build_flags = 
    -D CORE_DEBUG_LEVEL=2
    -D BOARD_HAS_PSRAM=0
    -D LCD_WIDTH=172
    -D LCD_HEIGHT=320
    -D PIN_LCD_MOSI=2
    -D PIN_LCD_SCLK=1
    -D PIN_LCD_CS=14
    -D PIN_LCD_DC=15
    -D PIN_LCD_RST=22
    -D PIN_LCD_BL=23
    -D PIN_TP_SDA=18
    -D PIN_TP_SCL=19
    -D PIN_TP_RST=20

lib_deps =
    bblanchon/ArduinoJson @ ^7.0.4
    moononournation/GFX Library for Arduino @ ^1.4.7
